server:
  port: 8080

#1 : adjust the hystrix timeout setting of the ribbon load balancer
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000
            
ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000
#1
  
#2 : mapped the request coming the gatewayURL/api/kicks/1 to kicks-serviceURL/kicks/1
zuul:
  prefix: /api
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000
  routes:
    kicks-service:
      path: /kicks/**
      serviceId: kicks-service
      stripPrefix: false
      sensitiveHeaders:
    kicks-inventory:
      path: /inventory/**
      serviceId: kicks-inventory
      stripPrefix: false
      sensitiveHeaders: 
#2
      