#Random the server port
server: 
  port: 0
  contextPath: /inventory

#Change Eureka Instance ID to be random
eureka:
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}