server:
  port: 8090
  contextPath: /kicks
spring:
  h2:
    console:
      enabled: true
      path: /console
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    url: jdbc:h2:~/test
    driverClassName: org.h2.Driver
    username: sa
    password: 