server:
  port: 0
  contextPath: /kicks
  
spring:
  h2:
    console:
      enabled: true
      path: /console
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  datasource:
    url: jdbc:h2:~/test
    driverClassName: org.h2.Driver
    username: sa
    password:

eureka:
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
    
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false